---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  identityProviders:
  - name: my_identity_provider
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret
  - name: gio-openid-idp
    mappingMethod: lookup
    type: OpenID
    openID:
      clientID: 0oaaaj9f3f2iwtlBw5d7
      clientSecret: 
        name: gio-openid-secret
      claims: 
        preferredUsername:
        - Email
        name:
        - name
        email:
        - email
        groups:
        - groups
      issuer: https://dev-45396272.okta.com
